apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: darraghk8s-com-tls
spec:
  secretname: darraghk8s-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: darraghk8s.com
  dnsNames:
    - darraghk8s.com
    - www.darraghk8s.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - darraghk8s.com
          - www.darraghk8s.com